language: cpp

sudo: false

matrix:
  include:
   # Linux
   - os: linux
     env:
      - CC=gcc-6
      - CC=g++-6
     addons:
      apt:
       sources:
         - ubuntu-toolchain-r-test
       packages:
         - g++-6
         - zlib1g-dev
         - valgrind
   # OSX
   - os: osx

install:
 # Build mrustc
 - make RUSTCSRC
 - make -j 2
 - make -C tools/minicargo

script:
 - make -f minicargo.mk output/libtest.hir
# libstd and hello_world
 - make test TAIL_COUNT=2
# rustc (DISABLED: llvm build)
# - make -f minicargo.mk output/rustc
# Tests
 - make local_tests -k
# - CC=gcc-6 make rust_tests -k
# cargo
# - make -f minicargo.mk output/cargo
# - cat output/cargo-build/cargo_dbg.txt
