language: cpp

sudo: false
os: linux
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-6
    - zlib1g-dev
    - valgrind

install:
 # Build mrustc
 - make RUSTCSRC
 - CC=gcc-6 CXX=g++-6 make -j 2
 - CC=gcc-6 CXX=g++-6 make -C tools/minicargo

script:
 - CC=gcc-6 CXX=g++-6 make -f minicargo.mk output/libtest.hir
# libstd and hello_world
 - CC=gcc-6 make test TAIL_COUNT=2
# rustc (DISABLED: llvm build)
# - CC=gcc-6 CXX=g++-6 make -f minicargo.mk output/rustc
# Tests
 - CC=gcc-6 CXX=g++-6 make local_tests -k
# - CC=gcc-6 make rust_tests -k
# cargo
# - CC=gcc-6 CXX=g++-6 make -f minicargo.mk output/cargo
# - cat output/cargo-build/cargo_dbg.txt
